export const lista = [
    {
    id:1,
    title:"Desayunar",
    completed:true
    },
    {
        id:2,
        title:"Meditar",
        completed:false
        },
        {
            id:3,
            title:"estudiar",
            completed:true
            },
            {
                id:4,
                title:"ejercicio",
                completed:false
                },
                {
                    id:5,
                    title:"almorzar",
                    completed:false
                    },
                    {
                        id:6,
                        title:"clases",
                        completed:false
                        },
                        {
                            id:7,
                            title:"bailar",
                            completed:false
                            },
                            {
                                id:8,
                                title:"limpiar",
                                completed:false
                                },
                                {
                                    id:9,
                                    title:"reir",
                                    completed:true
                                    },
                                    {
                                        id:10,
                                        title:"gintonic",
                                        completed:true
                                        }
    ]